version: '3.8'


networks:
  project_network:
    driver: bridge


services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-server
    hostname: rmq
    networks:
      - project_network
    ports:
      - "8080:15672"   # Management UI
      - "5672:5672"    # AMQP protocol port
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongooooooo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: solarch10
    networks:
      - project_network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  paymentmanager:
    container_name: payment_container
    build:
      context: ./PaymentManagement/PaymentManagement
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: ./PaymentManagement/PaymentManagement/Dockerfile
    environment:
      - RABBIT_ADDRESS=${RABBIT_ADDRESS}
    ports:
      - "8090:8080"  # Adjust port as needed
      - "8091:8081"

    networks:
      - project_network
    depends_on:
      - rabbitmq
      - mongodb

  exammanager:
    container_name: exam_container
    build:
      context: ./ExamManagement/ExamManagement
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: ./ExamManagement/ExamManagement/Dockerfile
    environment:
      - RABBIT_ADDRESS=${RABBIT_ADDRESS}
    ports:
      - "8092:80"  # Adjust port as needed
      - "8093:81"

    networks:
      - project_network
    depends_on:
      - rabbitmq
      - mongodb

  exameventhandler:
    container_name: exameventhandler_container
    build:
      context: ./ExamEventHandler/ExamEventHandler
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: ./ExamEventHandler/ExamEventHandler/Dockerfile
    environment:
      - RABBIT_ADDRESS=${RABBIT_ADDRESS}
    ports:
      - "8094:80"  # Adjust port as needed
      - "8095:81"

    networks:
      - project_network
    depends_on:
      - rabbitmq
      - mongodb
      
  schedulemanager:
    container_name: schedule_container
    build:
      context: ./ScheduleManagement/ScheduleManagement
      dockerfile: Dockerfile
      args:
        PROJECT_DIR: ./ScheduleManagement/ScheduleManagement/Dockerfile
    environment:
      - RABBIT_ADDRESS=${RABBIT_ADDRESS}
    ports:
      - "8096:8080"  # Adjust port as needed
      - "8097:8081"

    networks:
      - project_network
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  mongo-data:
    driver: local