version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-server
    hostname: rmq
    ports:
      - "8080:15672"   # Management UI
      - "5672:5672"    # AMQP protocol port
    restart: always