version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-server
    hostname: rmq
    ports:
      - "8080:15672"   # Management UI
      - "5672:5672"    # AMQP protocol port
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongooooooo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: solarch10
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local